branch-defaults:
  dev:
    environment: production
    group_suffix: null
global:
  application_name: Saffron API
  branch: null
  default_ec2_keyname: saffron_prod
  default_platform: Ruby 2.6 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
