default: &default
  adapter: postgresql
  encoding: unicode

development: &development
  <<: *default
  database: api_development
  username: postgres
  password:
  host: db
  pool: 5

test:
  <<: *development
  database: api_test
  host: <%= ENV['DB_HOST'] || 'db' %>

production: &production
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

staging:
  <<: *production