development: &default
  adapter: postgresql
  encoding: unicode
  database: api_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: api_test

staging:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>

production:
   url: <%= ENV['DATABASE_URL'] %>
